SELECT * FROM ROLES;
SELECT * FROM USUARIO;

INSERT INTO ROLES (NAME) VALUES ('ADMIN');
INSERT INTO ROLES (NAME) VALUES ('USER');

DELETE FROM USUARIO WHERE id_usuario = 1 ;

SELECT USUARIO.USERNAME, ROLES.NAME
FROM USUARIO
    JOIN USUARIOS_ROLES ON USUARIO.ID_USUARIO = USUARIOS_ROLES.USUARIO_ID
    JOIN ROLES ON USUARIOS_ROLES.ID_ROLE = ROLES.ID_ROLE
