--OPERACIONES QUE SE MANEJAN EN SQL 
--DDL->LENGUAJE PARA DEFINIR Y MODIFICAR LA ESTRUCTURA DE LOS OBJETOS DE LAS BASES DE DATOS->CREATE,UPDATE,ALTER Y DROP
--DML->LENGUAJE DE MANIPULACION DE DATOS-> SELECT, INSERT, UPDATE Y DELETE
--DCL->LENGUAJE DE CONTROL DE DATOS-> GRANT Y REVOKE


---CREACION DE UN NUEVO  USUARIO 

--MODIFICAR LA SESSION ACTUAL PARA LA EJECUCION DE SCRIPTS: CUANDO SE EJECUTARA UNA SENTENCIA 
--QUE SIGNIFIC TENER LOS PERMISOS NECESARIO DE ORACLE PARA QUE SE REALICE. SE MODIFICA LA SESION Y ENCONTECES PODEMOS
--EJECUTAR CUALQUIER TIPO DE OPERACION EN LA QUESE PUEDA VE AFECTADA MI BASE DE DATOS 
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; --EJECUTAR CON CTRL + ENTER
--CREACION DEL USUARIO Y SU CONTRASENA
CREATE USER DANY IDENTIFIED BY DANY12345;
--OTORGAR TODOS LOS PRIVILEGIOS AL NUEVO USUARIO 
GRANT ALL PRIVILEGES TO DANY;